### PR TITLE
Add bottom-left placement

### PR DESCRIPTION
**Pull request by cdjackson**

### CODE REVIEW

**Comment by rubenv** [comment]
How should I interpret `bottom-left`?

**Comment by rubenv** [comment]
As in: what's the difference with other placements?

**Comment by cdjackson** [comment]
It puts the popover in the bottom-left of the parent. If you use bottom, it’s centered in the parent (width wise) and if you use left, it’s off to the left. In my application, I’ve got a table and I want the popup to be below the line when clicked, but I want it on the left side of the screen - not in the middle (which would happen with bottom) as the popup might be wide…

The picture shows this (hopefully)…

(and thanks for the nice directive by the way - this should be a standard feature)

**Comment by cdjackson** [comment]
The picture didn't come through off the email...

screen shot 2015-01-09 at 12 10 29

**Comment by rubenv** [comment]
Makes sense. Could you fix the build failures? Looks good to merge then.

**Comment by cdjackson** [comment]
Thanks - will do (probably a little later).

**Comment by rubenv** [comment]
Released to NPM as `angular-rt-popup@1.0.1`.

Thanks a lot!

**Pull request merged**
